### ISSUE TITLE
Update `yaml`

### ISSUE THREAD

**Issue by fisker** [ikatyang/yaml-unist-parser#267]
When updating yaml to `v1.10.0` can't parse following code

```yaml
empty block scalar: >
 
  
   
 # comment
```

See https://github.com/prettier/prettier/issues/8349

**Comment by ikatyang** [comment]
This is the expected behavior, see https://github.com/eemeli/yaml/commit/7eafeb821d4a89d4de26f5b3798ee6e009e99b12 and yaml/yaml-test-suite#37 for more info.

**Comment by fisker** [comment]
Thank  you.
